### ISSUE TITLE
Why it is better then existing snapshot testing?

### ISSUE THREAD

**Issue by seclace** [netbeast/react-native-diagnose#1]
Hi! It is very interesting thing, but what goal are you want to reach by making it? 
What pros and cons for it? I think many folks want to know this info.

**Comment by jsdario** [comment]
Hi @seclace, maybe you can help me improve the rationale with a PR, it's basically what it says there

First of all snapshot testing is for interfaces and data structure **so they don't change**. The idea here is to test _behaviour_ of native functionality within the app. They have different purposes, **snapshot testing** is still be really valuable and you can have both, diagnose and snapshot in your app.

> * Testing native applications is complicated

Setting up the environment to test, specially if your app is not super orthodox can be really frustrating (navigation, redux / flux, and other structures may have side effects over recommended setup)

> * There are features that can only be tested on a device, unless mocked

Firebase, notifications, LAN network, bluetooth, device information, asynchronous tasks, device services... All those functionalities are really complex to mock, and have testing them without running on a device may be useless. Mobiles OSs impose their own restrictions.

> * You may want to test your app on a production build, before submit it to the stores

You can diagnose problems in your production build that might have passed through all tests without failing, because different devices (specially in Android) will have their own limitations.

**Finally:**
This is a integration tests framework, to test behavior on a finished app, has it's own pros and cons. It is a good complement to your unit / functional and snapshot testing suites.
